# This is a basic workflow to help you get started with Actions

name: Release

# Controls when the workflow will run
on:
  push:
   tags:
    - '*'

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

jobs:
  
  release:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout 🛎
        uses: actions/checkout@v3


      - name: Install dependencies 👨🏻‍💻
        run: npm ci
        
        
      - name: Run tests 🧪
        run: npm run test

      - name: Build files 🔨
        run: npm run build
        
      - name: Add release to Github 💾 
        uses: ncipollo/release-action@v1
        with:
          artifacts: "packages/display/dist/index.js,packages/interface/dist/index.js"
          token: ${{ secrets.GITHUB_TOKEN }}
